---
title: "text-for-final-report"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Experiment Question & Background

Does the orientation a store-bought apple is left on a counter impact how long it lasts at room temperature?

Banana hangers are little hooks that, as the name suggests, on which one can hang their bananas. They prevent the bananas from bruising and decrease the chance of exposing the banana flesh to oxygen, which in turn increases the longevity of the banana after it has been brought home from the store. But another reason that banana hangers keep bananas fresh for longer may be that it inverts the position in which they mature on a tree. While devices like banana hangers can help bananas to stay fresh longer, there are no such devices commercially available for apples. We propose to test if placing apples in specific positions will cause them to last longer at room temperature. 

### Importance of the experiment

Findings from this experiment have important implications for apple sellers, whose objective is to keep their fruits fresh for as long as possible without using any artificial preservatives. Companies are already expending significant resources to keep their product fresher for longer.  If we prove that simply placing apples in certain positions will inc